### ISSUE TITLE
TODO - kooBH

### ISSUE THREAD

**Issue by kooBH** [gogyzzz/iip_sph_pp#1]
---

# 던져둔것7
submat 이 ITER를 많이 받게되어있는데, 전부다 range 구조체로 변환 아니면 병용?
OMP schadule 적용하나?

CMAT DTYPE  : c
CMAT CTYPE  : cc -> u

CMAKE findBLAS 의 MKL 지원여부 테스트 - 잘 되는지-  
리눅스 환경에선 별도의 설치가- 환경변수 등록- 없는데, 설치가 있는지 ? 아니면 셋팅하는게 있는지?
-> 리눅스에서도 자동으로 MKL을 잡았다, 내가 환경변수에 몇가지 등록을 해놔서 그런듯한데. 제너럴하게
적용되는지 확인해야함

+ 가이드 만들기
MKL - 윈도우 함
OpenBLAS  - linux함 

역행렬 구하는 cpp 코드 https://www.quora.com/How-do-I-make-a-C++-program-to-get-the-inverse-of-a-matrix-100-X-100

알기쉬운 역행렬 구하기 https://www.mathsisfun.com/algebra/matrix-inverse-row-operations-gauss-jordan.html

크래머룰 위키 https://en.wikipedia.org/wiki/Cramer%27s_rule

정석적인 역행렬 구하는 코드 https://www.codeproject.com/Questions/754429/C-Program-to-calculate-inverse-of-matrix-n-n

긱4긱 역행렬 페이지 https://www.geeksforgeeks.org/adjoint-inverse-matrix/

정규 분포 난수 생성
https://stackoverflow.com/questions/2325472/generate-random-numbers-following-a-normal-distribution-in-c-c

Date | WHAT I DID 
---|---
7.13 |atomic 을 쓰려했으나, double이 안됨, critical section을 쓰면 너 - 무 느림, 교재에 있던것 같은 방법을 사용하거나, 다른 병렬화 sum 방법을 찾아보기로함<br> iip_wav.cu 작성 iip_blas_lv2.cu 작성, atomic을 이용한 cublas 함수구현은 보류.
7.16 |CTYPE -> cuComplex 캐스팅 매크로, blas_lv3. gemm 구현,  CMAKE openMP관련 버그 수정, 윈도우를 위한 cpu clock 독립적인 stopwatch 구현 , matrix transpose,hermitian을 3차원 배열은 2차원 배열의 batch라 보고 c 코드 구현
7.17| gemm native C 구현, OpenMP 관련한 버그 존재, 쓰레딩 데이터 관리에 문제가 있다
7.18|openMP의 문제는 임시변수가 private이 안되서 생긴것, 수정함, aABpbC 들 추가
7.19|일반적인 matmul 추가, blas_lv1 test코드 추가, set Identity matrix 추가, get inverse matrix 추가를 위해 blas_lv1 구현
7.20 | 행, 열 단위 스케일링. add 연산 추가.   memory_pool 에서 돌아가는 matrix 함수들 구현, mem.free,sub, trans,hermit 구현
7.23| 링크드 리스트를 쓰는 메모리풀 한번 만들어봄
7.24| 행렬단위 연산 - sqrt,pow,randu - 구현
7.25| 정규분포 난수 randn, round,ceil,floor,log,pow,exp 행렬연산 구현, 브로드캐스팅 mul,div 2차행렬 구현
7.26| srand(get_micro_sec()); 추가, 마이크로 초 단위 난수생성, clog2 구현(complex.h에 없다), iip_time.h 추가, repmat,reshape,shiftdim 구현, 다만 음수방향은 미구현
7.27|shiftdim, permutate 구현, Matlab bin 파일 IO 구현 , min_mat,max_mat 구현, getbydim,setbydim구현, CMAKE visual studio 호환 fix, gemm & axpy 에 batch 추가
7.30|diagonal, trace, 2X2 ~ 6X6까지 inverse, determinant 구현
7.31| LU decompostion.. wiki에서 가져욘 invert는 작동이 되는걸 확인했으나, LU 자체가 문제, 대부분의 오픈 코드는 divide by zero를 예외처리하지 않은코드고, 있더라도 이차원배열에 메이저가 달라서 다 고쳐야한다. 새로 짜는게 나을지 고치는게 나을지.. 짠 코드에 pivoting만 추가하면 될련지?

**Comment by gogyzzz** [comment]
checked issue.

**Comment by kooBH** [comment]
메모리 메니저 테스트

log는 GNU컴파일러으 
```
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:109:1: error: ‘log’ redeclared as different kind of symbol
 __MATHCALL_VEC (log,, (_Mdouble_ __x));
```
무언가와 충돌

이름을 memory_log로 변경

init 이 mother의 쿠다용 이닛과 중복, 조정 요망

**Comment by kooBH** [comment]
<details><summary>7.30</summary>

iip_matrix.h
```C
/**** set Diagonal ****/
void diagonal(MAT*mat);


```

</details>

**Comment by kooBH** [comment]
정리

**Comment by kooBH** [comment]
[mother_8h__incl.pdf](https://github.com/gogyzzz/iip_sph_pp/files/2276778/mother_8h__incl.pdf)

**Comment by kooBH** [comment]
![header](https://user-images.githubusercontent.com/39723411/43941599-b92cf3f4-9caf-11e8-90ee-9da14ef22c58.PNG)

**Comment by kooBH** [comment]
[mother_8h__incl.pdf](https://github.com/gogyzzz/iip_sph_pp/files/2276862/mother_8h__incl.pdf)
