### ISSUE TITLE
CBLAS의 사용에 대해

### ISSUE THREAD

**Issue by kooBH** [gogyzzz/iip_sph_pp#23]
리눅스 환경에서는 OpenBLAS를 사용하기 편합니다. 그냥 make 돌리고 make install 하면 뚝딱이니까요  
하지만 윈도우 환경에서는 얘기가 많이 다릅니다.  자료에 있는 바이너리 라이브러리 파일들은 비주얼 스튜디오 용이 아닙니다. 
https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio  
수동으로는 잘 되지도 않고, 포트란 컴파일- 수동으로 할 시, 포트란 컴파일러에서 계속 에러가 났습니다-하고 또 C 컴파일하는 식으로 하는데다가 
C 컴파일도 Visual Studio는 지원이 잘 되지도 않습니다.  

반면에 intelMKL 같은 경우에는 Visual  Studio 플러그인이 지원이 되어서, 옵션에서 사용만 체크하면 작동되게 되어있습니다. 

하지만 intelMKL은 리눅스 환경에서는 길디긴  
```bash
gcc  -DMKL_ILP64 -m64 -I${MKLROOT}/include  mkl-lab-solution.o  -Wl,--start-    group ${MKLROOT}/lib/intel64/libmkl_intel_ilp64.a ${MKLROOT}/lib/intel64/lib    mkl_sequential.a ${MKLROOT}/lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm -ldl  
```

컴파일 옵션을 달아야 합니다. 

리눅스는 openBLAS를 쓰고 윈도우는 IntelMKL를 사용하는 쪽으로하는게 좋을 것 같습니다.     
위키에 Windows에서 MKL을 사용하는 자세한 메뉴얼, Linux에서 OpenBLAS를 사용하는 메뉴얼을 추가하는 식으로 하면 괜찮을 것 같습니다.

**Comment by gogyzzz** [comment]
아주 좋은 생각이군요 그렇게 하세요

**Comment by gogyzzz** [comment]
이슈 닫겠슈
