### ISSUE TITLE
테스트 main 코드의 indentation이 고르지 않은 것

### ISSUE THREAD

**Issue by gogyzzz** [gogyzzz/iip_sph_pp#24]
제 사파리 브라우저에서 보면 아래처럼 나옵니다.

혹시 다른 분들은 정상적으로 표시 되나요?

```c
int main()
{
	init();

	MAT* a1, *sa1;
  MAT* a2, *sa2;
	MAT* a3, *sa3;

  a1 = zeros(4);
  a2 = zeros(3,4);
	a3 = zeros(2,3,4);

  sa1 = zeros(2);
  sa2 = zeros(2,2);
  sa3 = zeros(2,2,2);

	set(a1,2,1);
	print_MAT(a1);
	set(a2,1,2,1);
```

**Comment by kooBH** [comment]
그게 github의 뷰어는 tab 크기가 8인것 같습니다..

**Comment by Kandelion** [comment]
스페이스 문자랑 탭 문자가 혼용되어 있어서 그런것 같습니다..
언제 한번 소스 ident를 싹 정리해야될것 같습니다

**Comment by Kandelion** [comment]
[이 커밋](https://github.com/gogyzzz/iip_sph_pp/commit/ee696465aeb2bf28262ee2567d8a0c0cd31056c4)에서 현재 파일 ident 모두 정리했습니다.
모든 들여쓰기 문자는 TAB 문자(\t)로 되어있습니다.

**Comment by Kandelion** [comment]
ident 정리 하였으므로 닫겠습니다.
