### ISSUE TITLE
VS 세팅 진행상황

### ISSUE THREAD

**Issue by Kandelion** [gogyzzz/iip_sph_pp#28]
현재 포맷 완료했고 비주얼 설치중입니다. 2013은 정상적으로 설치되었고, 2015는 설치하지 않고 2013, 2017만 설치할 계획입니다.

**Comment by Kandelion** [comment]
2013, 2017 설치는 끝났습니다. Clean 설치상태(윈도우만 설치된 상태)에서 Visual Studio 2013, 2017, CUDA 9.0 Toolkit, Cmake 만 설치된 상태이고 이외에는 아무것도 설치되어 있지 않은 상태입니다. 2017로 CMake를 시도하면 이전과 동일한 오류가 나는것으로 보아 본혁이가 쓴 노트북에서 뭔가 설정이 되어있는 것으로 보입니다. 별다른 설정이 없이 되는것은 2013 이전 버전만 인것 같습니다.  
  
추가로, 지금 2013 버전 프로젝트 생성은 잘 되지만 rt.lib 파일을 못찾고, cublas.lib 또한 못찾고 있습니다. cuda 설치시 cublas는 자동으로 설치되는 것이라 들었는데... 원인을 모르겠네요.

**Comment by Kandelion** [comment]
cmake에서 rt를 제거하고 cublas 라이브러리 위치를 수동으로 잡아줘도, 다음과 같은 에러가 발생합니다.
![default](https://user-images.githubusercontent.com/30633906/42554221-025193f8-851f-11e8-9643-01b4f8685c83.PNG)
자동으로 잡히지 않고 수동으로 잡아줘서 그런것 같습니다. 지금 clean window 상태이니, 설정이 꼬였을리는 없고 윈도우는 뭔가 추가로 세팅을 해야하는게 아닐까 싶습니다..

**Comment by gogyzzz** [comment]
읽기만해도 같이 암에 걸리는 상황이군요 
그러면 본혁이가 추가로 한 세팅도 세팅이지만 그 전부터 우리 연구실 컴에 어떤 세팅이 이미 되어 있었다던가...?

**Comment by Kandelion** [comment]
@gogyzzz 네 아마 그런것 같습니다.. 우선은 포맷하고 다시 진행한거라 제 세팅이 꼬여있지는 않을테니까요

**Comment by Kandelion** [comment]
음 rt를 계속 회피하면서 cublas를 찾아서는 안될것 같습니다 우선 rt.lib link문제부터 해결해보겠습니다. 무슨 라이브러리인지는 정확히 모르겠지만...

**Comment by gogyzzz** [comment]
네 일단 출근 가능하신가요 출근 부탁

**Comment by kooBH** [comment]
rt는 CMakeLists.txt #75  target_link_libraries(out ${LINKLIBS} rt cublas) 에서 없애도 되요

그 부분은 복붙한건데 없어도 잘 돌아갑니다

**Comment by Kandelion** [comment]
@gogyzzz 앗 집에서 할 생각이었는데 그럼 출근하겠습니다

@kooBH 그럼 rt는 그냥 무시해도 되는건가 안그래도 지금 전체 C드라이브내에 rt.lib라는 파일 자체가 없어서 당황스러운데

**Comment by Kandelion** [comment]
점심만 밖에서 해결하고 가겠습니다

**Comment by gogyzzz** [comment]
넴 하루에 적어도 30분정도는 보도록 합시다

**Comment by Kandelion** [comment]
넵

**Comment by Kandelion** [comment]
VS 세팅 완료되었으므로 닫겠습니다.
