### ISSUE TITLE
header 파일의 함수 형태에 타입과 변수 이름을 함께 넣어주시길 요청

### ISSUE THREAD

**Issue by gogyzzz** [gogyzzz/iip_sph_pp#44]

**Comment by Kandelion** [comment]
[iip_blas_lv1.h](https://github.com/gogyzzz/iip_sph_pp/blob/master/header/iip_blas_lv1.h)의 경우는 대부분 변수 이름이 함께 기록되어 있습니다.

**Comment by gogyzzz** [comment]
@Kandelion @kooBH 다른 함수는 어떤가요? 다른 함수도 다 해주시고 나면 issue 닫아주세요

**Comment by kooBH** [comment]
제가 한 건 하나도 안되어있습니다 ;;

**Comment by kooBH** [comment]
matrix.h만 하면됩니다
