### ISSUE TITLE
여러 형태의 matmul 요청

### ISSUE THREAD

**Issue by gogyzzz** [gogyzzz/iip_sph_pp#45]
```c
// create A, B, C
range tmpr1, tmpr2, tmpr3;
tmpr1 = set_range(MAT* A, -1,-1,  0,1,  -1,-1); // 중간 차원은 지금  0~1이 아니라 0번째만 접근된 것임
tmpr2 = set_range(MAT* B, -1,-1,  0,1,  -1,-1);
tmpr3 = set_range(MAT* C, -1,-1,  0,1,  -1,-1);

matmul(A, B, C); 
matmul(A, B, C, tmpr1, tmpr2, tmpr3);

// 아래 캐스팅이 문법적으로 되는지?
caABpbC((CTYPE){1, 0}, A, B, (CTYPE){0,0} C)
// 안될 경우라도 그냥 alpha와 beta는 CTYPE으로 할 것

```

broadcasting 연산이 아니기 때문에 아래와 같이 동작해야 함

| example | answer | note |
|---|---|---|
|n x m x 1 * m x n x 1 | n x n x 1 |  |
|n x m x 1 * 1 x m x n | n x n x 1 |  |
|1 x n x m * 1 x m x n | n x n x 1 |  |
| n x 1 x m * 1 x m x n | n x n x 1 |  | 
| 

|(n x m x l)*(l x m x 1)| n x m x m | l_value의 맨 끝과 r_value의 앞 차원(l)이 merge. 논의 필요 |
|(n x m x l)*(l x m x n)| error | 우리꺼는 4차원까지는 지원하지 않음 |
|(n x m x l)*(l x 1 x 1)| n x m x 1 | |

| name | representation | note  |
|---|---|---|
| matmul | MAT* A, MAT* B, MAT* C,  | A * B -> C |
| matmul_range | MAT* A, MAT* B, MAT* C, range* ra, range* rb, range* rc |  |
| aABpbC | DTYPE alpha, MAT* A, MAT* B, DTYPE beta, MAT* C |  |
| aABpbC | DTYPE alpha, MAT* A, MAT* B, DTYPE beta, MAT* C, range* ra, range* rb, range* rc  |  |
| aAtBpbC |   |  |
| aABtpbC |   |  |
| aAtBtpbC |   |  |
| aA?B?pbC_range |   | 위 함수들에 range를 적용한 함수 |
| caABpbC | CTYPE alpha, MAT* A, MAT* B, CTYPE beta, MAT* C | 너무 많다 |
| caABtpbC |   |  |
| caAtBpbC |   |  |
| caAtBtpbC |   |  |
| caAhBpbC |   |  |
| caABhpbC |   |  |
| caAhBhpbC |   |  |
| caAhBtpbC |   |  |
| caAtBhpbC |   |  |
| caA?B?pbC_range |   | 위 함수들에 range를 적용한 함수 |

**Comment by gogyzzz** [comment]
matmul_range 라는 식으로 함수 이름을 붙이기에는 너무 길어서 _r 만 붙이려고 하는데 어떻게 생각하시나요

**Comment by kooBH** [comment]
?aA?B?pbC 는 blas_lv3인자만 다른것이니 blas_lv3에 만들겠습니다.
matmul_ran 정도가 저는 좋다고 생각합니다. 조금 길긴한데 _r은 바로 이건 뭐다 하는게 안올수도 있을 것 같네요

**Comment by kooBH** [comment]
range가 없는 연산들은 blas_lv3에 만들었습니다

**Comment by gogyzzz** [comment]
@kooBH 일단 _range로 합시다

**Comment by gogyzzz** [comment]
@kooBH 
matmul 연산에서 batch broadcasting을 하는 내용을 내일 얘기합시다.

**Comment by kooBH** [comment]
from haeyong

matmul
( M x N x B ) * ( N x M x 1 ) = ( M x M x B ) 
( M x N x B ) * ( N x M x B ) = ( M x M x B ) 
( M x N x 1 ) * ( N x M x B ) = ( M x M x B ) 

element-wise(mul, add, div)
( M x 1 x B ) * ( M x N x B ) = ( M x N x B )
( M x 1 x 1 ) * ( M x N x B ) = ( M x N x B )
... 12가지 case

**Comment by gogyzzz** [comment]
맷멀 함수는 현재까지 만들어진 것만 쓰고, 이 이슈는 닫도록 하겠습니다.
