### ISSUE TITLE
Transpose 메모리 관련

### ISSUE THREAD

**Issue by Kandelion** [gogyzzz/iip_sph_pp#52]
우선 몇가지 방법이 있습니다.
* bit flag를 이용, swap을 통해 연산한다.
* buffer를 이용, 메모리값을 저장해가면서 transpose를 수행한다. 
* 통짜로 가져다 놓고 복사해서 transpose한다.
* 메모리 추가할당이 없이 그냥 swap을 하면서 매번 check를 수행하여 연산한다.

위에서부터 3가지 방법 모두 추가적인 메모리를 아예 쓰지 않고는 연산이 불가능 하며, 그나마 bit flag가 추가 할당을 안해도 될만합니다만... 차후 worst case를 보시면 만만찮습니다. 마지막 방법은 메모리 추가할당이 없이 연산을 한다고 해두었는데, 이 방법은 메모리를 추가로 안 쓰는대신 시간 복잡도가 끔찍하게 높아지며(O(n!)), data size가 클 경우 transpose에 아주 오랜 시간이 걸릴 수 있습니다.

UINT N이 최대 data size라고 가정하였을 경우(data size가 16GB의 메모리를 차지)입니다.
data형태는 Worst Case를 가정하고 계산하였습니다.

* bit flag를 이용하였을 때 추가 메모리
> 512 MB가 추가로 필요합니다.
data size 1마다 1bit씩 flag가 필요하며 결국 data size / 32와 같은 크기입니다.

* buffer를 이용하였을 경우 추가 메모리
> 32GB가 추가로 필요합니다.
이 경우 다소 특이한데, 1줄짜리 1 by 2^32 의 배열이 들어오면 이렇게 통째로 복사하는것보다 더 많은 메모리를 요구합니다. Best Case는 2^16 by 2^16으로, 이러면 512Kbyte의 추가 메모리만 가지고 연산이 가능합니다. 한마디로 X by Y size에서 X, Y가 크게 다르지 않으면 메모리를 꽤 절약할 수 있지만 길쭉한 형태로 갈수록 성능이 떨어지게 될것으로 보입니다.

* 통짜로 가져다 놓고 복사할 경우
> 정직하게 Data와 같은 16GB가 추가로 필요합니다.
말그대로 통째로 복사하고 다시 가져다 쓰는 것이므로 Data Size와 정확히 동일한 양의 메모리를 요구합니다.

* 메모리 추가할당 없이
> 메모리는 추가로 필요하지 않으나, transpose(size1by1) = 1의 cost라 할 때, 2^32!(팩토리얼) 의 cost가 소요됩니다. 함부로 도전했다가는 이 연구실을 떠날때까지 연산할수도 있겠군요!

***

데이터 사이즈가 16GB로 좀 극단적이긴 하지만, 사용자 메모리가 받쳐준다면 연산이 가능해야 할 size이고, 실제로 얼마나 큰 데이터를 이용할지 모르기 때문에 대충 ~~정도의 데이터를 쓸것이다~~ 하고 구현할수가 없어 worst case를 생각해보면... 통짜로 가져다 놓고 복사해서 쓰거나, bit flag를 사용하는 것이 가장 나아보입니다. 다만, bit flag 방식이 머릿속으로만 생각한 swap 알고리즘이고 실제로 올바르게 작동하는지는 확인이 되지 않았으므로 좀더 고민이 필요해보입니다.

**Comment by Kandelion** [comment]
그리고 저도 오늘은 이만 퇴근해보겠습니다 하하

**Comment by kooBH** [comment]
저는 bit flag가 가장 괜찮다고 생각합니다. 1/64 ~ 1/32 크기의 배열이면 충분하니까요.
제가 생각했던건 각 인덱스별로 transpose 했는지 않했는지 플래그를 세우고, [0] 부터 transpose하되 인덱스가 1 : 1로 swap 되는게 아니기 때문에, 덮어씌우는 자리의 원소를 다시 전치( 덮어씌운 애가 있는 자리는 전치했다는 표시로 플래그를 true) 하면서 나가면 원래자리로 돌아올 수도 있게 됩니다. 이때는 해당 자리는 플래그가 true기 때문에 다음 인덱스로 넘어가면서 flag가 false인 인데스를 찾으면 거기서 다시 transpose 하는 식으로 끝까지 가면 된다고 생각합니다. 시간은 data_size(처음부터 끝까지) + data_size(전부다 transpose )라고 일단은 생각하는데, 구현한다면 개선할 사항이 있을 거라고 생각합니다

**Comment by gogyzzz** [comment]
3번으로 해주세요. 여러분의 지적 욕구를 채워드리지 못해 안타깝습니다

```c
trans(MAT* src, MAT* dst); //

MAT A, B; // 미리 할당해야 함

trans(A, B);
```

**Comment by kooBH** [comment]
메모리풀 하는 걸로 됐으니 닫겠습니다
