### ISSUE TITLE
(예상: 2 days) 메모리 풀 구현

### ISSUE THREAD

**Issue by gogyzzz** [gogyzzz/iip_sph_pp#54]
@Kandelion @kooBH 메모리 풀 관련해서 논의한 내용을 여기 써주세요

**Comment by gogyzzz** [comment]
할당 요청된 메모리가 풀의 사이즈를 초과했을 경우, 더 많은 메모리를 얼마나 늘릴 것인지에 대해 옵션을 줄 수 있는 형태면 좋겠습니다.

예를 들어
선형적으로 늘리기 - 요청한 만큼만 더 늘리기
지수배로 늘리기 - 현우가 말한 것처럼 사이즈에 따라 지수배로 늘리기

등이 있을 수 있네요. 일단 저 두개에 대한 옵션만 있어도 될 것 같아요

**Comment by Kandelion** [comment]
@gogyzzz 메모리를 늘리는 부분에 관해서는 많은 방법이 있겠지만 가장 널리 쓰이고 있는 방법은 2배씩 늘려가며 할당하는 방법인 걸로 알고있습니다. 요청한 만큼만 더 늘리게 되면 다음번 호출이 있을 경우 또다시 추가 할당을 해줘야 할 가능성이 높고, 일정 배수만큼만 추가 할당을 하게 될 경우 페이지의 개수가 많아져서 링크드리스트같은 추가적인 자료구조가 필요하게 됩니다. 또한, 하나의 페이지보다 큰 메모리는 할당이 어렵기 때문에 하나의 페이지 자체가 상당한 크기를 가져야하게 됩니다. 단 1개의 변수만 할당한다 해도 내부적으로 페이지 단위로 malloc을 하기 때문에 4바이트를 위해 수MB를 할당받아야 할수도 있습니다. 반면 지수적으로 증가하는 방식으로 추가 할당을 하게 되면 하나의 페이지의 크기가 급격히 증가하므로 페이지 크기의 한계로 할당하지 못하는 경우가 크게 줄어들고, 한번 추가 할당을 하면 기존 할당 메모리만큼의 공간이 확보되므로 짧은 시간내에 추가 할당을 요구하게 되는 경우가 상당히 줄어듭니다.

**Comment by Kandelion** [comment]
@gogyzzz 메모리풀 초기 사이즈를 정해야 하는데, 초기 사이즈가 너무 작으면 첫 페이지가 낭비되어 버립니다. 일반적으로 몇 size 정도의 데이터를 다루게 되는지 알수 있을까요?

**Comment by gogyzzz** [comment]
@Kandelion 1024 * 1000 * 8 사이즈의 행렬을 열개 이내로 다루는 경우가 최악의 최악인 것 같습니다

**Comment by gogyzzz** [comment]
@Kandelion 2배씩 늘어나는 방안으로만 가도록 하죠.

**Comment by Kandelion** [comment]
@gogyzzz 최악의 경우 보다는 일반적인 경우의 데이터 사이즈가 필요합니다. 혹시 일반적인 경우의 데이터 사이즈를 대략이나마 알수 있을까요?

**Comment by gogyzzz** [comment]
@Kandelion 

16000 * 5 * 4 정도의 변수가 1개,

1024 * 300 사이즈의 변수가 2개 있는게 보통인 것 같습니다.

**Comment by Kandelion** [comment]
제약사항을 몇가지 정하겠습니다.

* 본 프로젝트에서 메모리 풀을 통해 한번 할당받은 메모리는 함수의 종료 전에 반드시 반환해야합니다.
* 메모리 풀을 통한 할당/해제를 시도할 때, for문과 같은 반복문 내에서 반복적으로 할당 및 해제를 시도하는 경우를 피하는 것이 좋습니다. 또한, 만일 반복적인 할당 해제를 시도할 경우 반드시 할당받은 메모리를 먼저 해제 요청하고 나서 다시 할당을 받아야 합니다. 이 순서를 지키지 않고 할당 해제를 반복할 경우, 메모리 빈공간을 활용하기 위해 별도의 처리가 추가적으로 필요한데, 이러한 각종 처리까지 반영되기 시작하면 단순히 malloc을 덜 사용하려다가 오히려 배보다 배꼽이 커질수도 있습니다.

**Comment by gogyzzz** [comment]
@Kandelion 메모리 할당과 해제는 제작하는 함수내에서만 사용하는 것으로 하고, MAT* 을 생성하고 해제하는 등의 인터페이스는 그대로 유지합시다. 
@Kandelion 님 말씀은 사용자가 임의로 메모리풀을 통한 할당을 남용할 가능성이 있다는 거죠?

**Comment by gogyzzz** [comment]
@Kandelion 메모리풀을 사용하면 알고리즘 도중에 행렬을 선언해도 전혀 속도저하가 없어서, 남용될 여지가 있긴 한데 이건 사용자 책임으로 맡기고 가급적이면 필요한 행렬은 처음에 전부 선언하고 해제를 반드시 부탁한다는 쪽으로 가이드를 줄 수 밖에 없을 것 같네요

**Comment by Kandelion** [comment]
@gogyzzz 아뇨 저희가 개발하는 함수내에서도 위의 규칙을 지켜야합니다. 순수한 malloc()과 같이 사용하려면 메모리의 빈공간에 대한 관리, 파편화에 대한 관리 등이 모두 포함 되어야합니다. 하지만 저희는 malloc()을 사용하려는 이유가 함수내에서 MAT의 데이터에 대한 추가 메모리 공간이 필요하여 대용량을 할당하려는 것이고, C++이 아니므로 여러곳에 메모리 세션이 유지될 필요가 없습니다(현재 구조에선 그래선 안됩니다). 따라서 메모리 풀에 대한 간단한 사용규칙만 따르면, 메모리의 파편화와 같은 상황에 대한 처리 루틴이 생략될 수 있으며 메모리 할당에 대한 처리도 훨씬 빠르게 할수 있습니다.

**Comment by Kandelion** [comment]
@gogyzzz 아 메모리 풀에 대해 약간 잘못 전달된 부분이 있는것 같습니다... 전혀 속도 저하가 없는 것은 아니고, 메모리를 떼어서 주는 과정에서 본디 위와 같은 메모리 파편화의 방지, 페이지의 관리 등을 위해 약간의 추가 작업이 필요하기 때문에 전혀 속도 저하가 없는 것은 아닙니다. 다만 그 속도가 malloc()에 비하면 빠를 뿐이며, 부하가 없는것은 아닙니다. 특히, 제안한 규칙을 따르지 않고 마구 사용하는 경우에는 메모리 파편화 처리를 해야하므로 좀 더 고도화된 메모리 분배를 사용하게 되며 이 경우 다소의 연산이 필요해집니다(그래도 malloc()보다는...).

**Comment by gogyzzz** [comment]
@Kandelion 1따봉 드리며 이것을 Usage로 하겟씁니다

**Comment by Kandelion** [comment]
완결되었으므로 닫겠습니다.
