### ISSUE TITLE
github milestone 기능에 대한 안내

### ISSUE THREAD

**Issue by gogyzzz** [gogyzzz/iip_sph_pp#65]
milestone은 issue의 상위 개념이라고 합니다.

https://github.com/okjsp/okmakeover/wiki/Guide-Github-Milestone-%ED%99%9C%EC%9A%A9%EB%B0%A9%EB%B2%95

내용을 대강 보니 issue도 시간 순으로 잘 정리할 수 있는 것 같습니다.

내일은 @kooBH 님과 얘기를 하면서 milestone의 사용법을 테스트 해보기로 합시다.

**Comment by kooBH** [comment]
프로젝트를 활용하기로 했으니 닫겠습니다
