### ISSUE TITLE
ASSERT

### ISSUE THREAD

**Issue by kooBH** [gogyzzz/iip_sph_pp#67]
```C
/**** ASSERT MACRO ****/
#define DIM_INVAL 1

/**** ASSERT FUNCTION ****/
#define ASSERT(x)\
{if(x==1){printf("WARNING(%s) : invalid dimension\n",__func__);return;}\
\
\
\
}\
```
일단 이런식으로 하려고합니다. 사용은 void 함수 내에서만 하고요

**Comment by gogyzzz** [comment]
@kooBH DIM_INVAL은 어떻게 사용되나요?

**Comment by kooBH** [comment]
연산해야하는 행렬의 차원수가 맞지 않을때 사용합니다

예를 들면 1X3 3X1 mul_elements를 하면 C가 3X3이어야 합니다. 
이때 C의 크기가 3X3이면 ASSERT(DIM_INVAL)을 합니다.
