### ISSUE TITLE
Wrong Codes

### ISSUE THREAD

**Issue by Kandelion** [gogyzzz/iip_sph_pp#8]
File : `iip_matrix.h`
===
- Description
  
 다음 함수 선언은 .cu 파일 내에만 작성하고 본 헤더파일에는 작성할 필요가 없습니다(작성되지도 않습니다.).
```
__global__ void cu_fill(DTYPE*,UINT,DTYPE,UINT);  
__global__ void cu_cfill(CTYPE*,UINT,DTYPE,DTYPE,UINT);
```

**Comment by kooBH** [comment]
일단은 헤더에 선언해야하지 않나요

```
/home/bonhyeok/git/iip_sph_pp/iip_matrix.cu(282): error: identifier "cu_fill" is undefined  
/home/bonhyeok/git/iip_sph_pp/iip_matrix.cu(302): error: identifier "cu_cfill" is undefined   
```
```C++
#if USE_CUDA
#endif
```
로 감쌀꺼라  문제는 없다고 생각합니다

**Comment by Kandelion** [comment]
헤더에 선언할 필요없이 그냥 .cu 파일 상단에 선언해도 되고 지금 헤더에다 선언 같이 해둘거면 이 쿠다 함수들에 대해서도 각각 전부 USE_CUDA 꼼꼼히 감싸서 커밋해줘 지금 쿠다 사용 여부랑 관련없이 헤더에 선언된 형태로 작성되있는데 이러면 빌드 실패함

**Comment by Kandelion** [comment]
그리고 CMake 내꺼에서 쿠다 툴킷을 못찾아서 컴파일 시도 자체가 안되는데 혹시 이유 아는지..?
이 PC에서 쿠다 코딩 이미 여러번 진행해봤고 지금도 쿠다 연산 이용한 애플리케이션 빌드 잘 되고 실행 잘 돌아감

**Comment by Kandelion** [comment]
다른 스레드에서 논의하였으므로 닫겠습니다.
