### ISSUE TITLE
Cuda codes header file

### ISSUE THREAD

**Issue by Kandelion** [gogyzzz/iip_sph_pp#9]
File : `*.cu`
===
- Description
  
 쿠다 코드 또한 런타임 헤더가 필요합니다. 쿠다 헤더 파일의 확장자는 `*.cuh`이며, 기본적으로 2가지의 헤더를 include 하여야 일반적인 작업이 가능해집니다.
```
#include "cuda_runtime.h"
#include "device_launch_parameters.h"
```
위의 2가지 파일을 모두 include 하여야 하는데, 쿠다 파일 또한 여러가지이고 현재 쿠다관련 전역변수도 있으니 `*.cu`파일들이 공통으로 include 할 수있는 `mother_cuda.cuh`와 같은 파일을 생성하는 것이 어떨까합니다.

**Comment by kooBH** [comment]
쿠다관련 전역변수들은   
헤더에서 
```C+
#if USE_CUDA
#endif
```
로 감쌀예정이고

굳이 나눌필요는 없을 것 같네요
그리고 헤더 확장자는 정해진게 아니라서 헷갈릴까봐 .cuh를 쓰는데
저희는 그냥 .h에 다 넣어버릴 꺼라 그냥가도 될거 같습니다

**Comment by Kandelion** [comment]
아 지금 보니까 전역변수가 제대로 안되있네
`iip_type.h` 여기에도 static으로 전역변수 있는데 이 친구들 그럼 삭제 좀 해주고

이슈 열었던거 임의로 닫지 말자..
다른 사람은 아직 해당 이슈에 대해 해결되었다고 생각하지 않을수도 있고 그냥 닫아버리면 해당 이슈에 피드백이 전혀 없잖아

**Comment by kooBH** [comment]
static 한거는 머지하면서 꼬여서 들어간거같아요, 그건 없앴구요
아래 이슈는 이 이슈하고 겹쳐서 없앴었어요

지금은 mother 에 extern 으로 있고
.cu에서 선언 해 놨는데
동작엔 이상이 없습니다.

헤더를 하나로 하려는데, 지금 코드는 어쩔수 없이 쿠다 함수 따로해야해서 두 개인건데  
새로운 함수 추가하려면 지금처럼 헤더 하나인게 관리하기는 더 편할꺼 같아요
헤더가 두개면 .h 앤 A 함수가 있는데 .cuh 에도 있는지 확인해야하고 번거로워서요

**Comment by Kandelion** [comment]
지금 너 코드에서는 당연히 너의.cu에 선언되있으니 작동이 잘 되는데 내 쿠다 코드에서는 해당 변수가 접근이 안되지 않을까 mother를 include를 안하고 인자를 넘겨받는 부분도 전혀 없는데 어떻게 접근을 하지

**Comment by Kandelion** [comment]
그리고 지금 헤더파일에서 비슷한 함수끼리는 한눈에 보기 위해서 한 파일에 쓰려는 거지?
그럼 함수 한종류마다 USE_CUDA 전처리기 2줄씩 다 들어가야되지만 그래도 그 방식이 더 마음에 든다는 거지?

**Comment by kooBH** [comment]
extern 써야해서 .cu에 선언은 해줘야해요. 컴파일시 헤더구조가 어떻게 되는지는 잘 모르겠지만
mother.h에서 변수들에 값도 잘 넣어주고 .cu에서 값도 잘 받아와요

**Comment by kooBH** [comment]
2줄정도 씩은  불편해도 파일 2개보단 편한거 같아요

**Comment by Kandelion** [comment]
그럼 파일은 전처리기 꼼꼼하게 해서 하는걸로 하고

.cu가 다른 .cu파일에서 그 변수값을 받을 방법이 있냐는 건데..
지금 iip_maxrix.cu 에 선언되있고 그쪽에서 변수를 쓰는 거잖아
근데 그게 다른 외부 cu파일인 iip_blas_lv1.cu에서 mother include 없이 변수를 가져올 방법이 있냐는 것

**Comment by Kandelion** [comment]
지금 현재 구조가
`iip_type.h` : 모든 소스에서 이 파일에 접근가능
`*.h(etc)` : 각자 자신의 모듈의 선언부
`mother.h` : 이 파일을 통해 모든 소스에 접근 가능

이런 형태인데 mother에 extern으로 선언해둬도 iip_blas_lv1.cu는 include하는게
 `iip_blas_lv1.h` > `iip_type.h`
이렇게만 include가 이루어지는데 `max_thread` 같은 변수의 존재여부를 모르지 않나

**Comment by kooBH** [comment]
iip_type 애다 extern으로 선언하고
mother에서 선언하면

더이상 선언할 필요는 없네요

**Comment by Kandelion** [comment]
mother에서 선언할 필요가 있어?
 그냥 어떤 .cu에 정의 해두고 iip_type에다가 extern 걸어주면 끝 아닌가
main.c에서 해당 쿠다 변수에 대해 접근할 일이 있나

**Comment by kooBH** [comment]
mother.h 에서 초기화를 해주기 때문에 mother.h 에서 한번더 선언을 해줘야해요
iip_type은 여러번 include 되서 초기화를 못 넣어요

**Comment by Kandelion** [comment]
음? 그냥 쓰면 되잖아
mother.h에서 iip_type.h에 있는 변수 접근 가능하잖아 어차피 extern으로 iip_type에 선언되있으니까 그 변수들 그냥 mother.h에서 가져다 쓰면 되는거 아냐? 접근이 안되?

**Comment by kooBH** [comment]
extern 자체는 깡통이라..  접근 안돼요..

**Comment by Kandelion** [comment]
???? extern이 깡통이니까 .cu에 정의를 해줘서 거기에 접근하는 거잖아

**Comment by Kandelion** [comment]
헤더에 extern을 써서 선언해주는 이유가 다른 파일에서 일일이 extern 남발하지 않고 헤더 한곳에 정리해서 선언해둠으로써 소스코드에서는 헤더의 extern을 보고 해당 symbol을 따라 .cu에 있는 파일에 접근하는건데 extern이 깡통이라 접근이 안된다면 헤더에 extern을 왜 쓰는거야

**Comment by kooBH** [comment]
전체적으로 어떻게 굴러가는지 긴가민가한데 
iip_type에 extern 선언  
mother.h에 선언하고 초기화

이것만 했는데, 돌아는 갑니다

**Comment by Kandelion** [comment]
변수를 헤더에서 접근하려 들어서 안되는건가? scope자체는 닿을텐데

**Comment by Kandelion** [comment]
@kooBH 음 너 브랜치에서 작업중이지? 해놓은거 코드 한번 보고 싶은데 푸시 해줄수 있니

**Comment by kooBH** [comment]
제 브랜치로 푸시 했어요

**Comment by kooBH** [comment]
모든 .cu에 넣어둬야 된다고 생각은 했는데 mother.h 에만  
cublasHandle_t handle;  
UINT max_thread;  
UINT max_block;  
해둬도 돌아가더라고요  
일단은 저 변수들 사용하는 코드애는 다 넣어 둘께요

**Comment by Kandelion** [comment]
아냐아냐 .cu 아무거나 하나만 골라서 넣고 나머지 .cu에는 넣지마 그리고 mother.h를 include하는애가 지금 하나밖에 없어서 문제가 없는거지 저걸 2개 이상 include하는 순간 바로 재정의 에러터져

**Comment by kooBH** [comment]
그렇네요

**Comment by Kandelion** [comment]
잘 되니 잘되는거면 이 이슈는 닫자

**Comment by kooBH** [comment]
ㄱㄱ
