### ISSUE TITLE
복소수 행렬 이슈와 이슈

### ISSUE THREAD

**Issue by kooBH** [gogyzzz/iip_sph_pp#91]
파도파도 끝이 없네요..

# 연산 오류

실수일경우, 수식은 잘 돌아가는 것 확인함  
다만 복소수의 경우 
```
4.0000 + 2.0000i   3.0000 - 4.0000i   0.0000 + 1.0000i
   0.0000 + 2.0000i   4.0000 + 0.0000i   3.0000 - 1.0000i
   2.0000 + 2.0000i   5.0000 - 1.0000i   0.0000 + 0.0000i
```
이 행렬을 처리할때

```
Y[4].re : 0.000000
Y[4].re = -0.026829 * -0.020732 - 2.000000 * 0.013415
Y[4].im = 0.000000 * 0.013415 - -0.041463 * -0.020732

역행렬
+0.1829 -0.3537| -0.0878 -0.0902| +0.1512 +0.4610| 
-0.2195 +0.0244| -0.0268 -0.0415| +0.3585 -0.1732| 
+0.0976 -0.1220| +0.2732 +0.0585| -0.1927 +0.0659| 

A * A^(-1)
+1.0000 +0.0000| -0.4756 -0.2805| +0.0000 +0.0000| 
+0.0000 +0.0000| +0.9512 -0.4390| +0.0000 +0.0000| 
+0.0000 +0.0000| -0.1707 -0.5366| +1.0000 +0.0000| 
```
역행렬의 [4]만 다르다. 나머지는 matlab 과 같고 행렬식도 잘 나온다

다른 경우에도 변수가 0.0이 들어가 있어서(4by4의 경우 행렬식에 0이 들어가 있었다) 연산이 잘 되지 않는다.  
어디에서 꼬이는지 알아봐야함.  

추가로 지금은 3,4 까지만 해놨지만 마지막에 행렬 전체에 행렬식 곱할떄, 임시변수를 통해 연산하는걸 추가해야한다. (.re = 한뒤에 .re를 사용해야하기 때문에)

+ 이부분은 허수부 연산에 자기 자신의 실수부가 있는 경우 임시변수 처리가 다 안되서 그런것같다 .. 다 확인하고 추가하면 될듯부

# symbol lookup error: ./iip_sph_pp_blas: undefined symbol: LAPACKE_zgetrf

LAPACK 자체를 링크해서 연산하는 것에는 문제가 없지만. OpenBLAS 사용시 헤더만 포함이되고 코드가 없다는 것 같다. Openblas 자체에 포함은 되있다는 것 같은데(빌드 옵션에 USE_LAPAKC이 default 라함), 라이브러리 빌드 옵션의 문제인지 cmake 에서 링크가 잘 안된건지 (libopenblas.a에 lapack이 포함 되어 있다면 그럴것 같진 않다)   다른 실수가 있는 건지 알아봐야겠다    
헤더로는  
```C
#include "lapacke.h"
```
사용  
  
visual stduio 에서 MKL로는 잘 돌아가는 것 확인함.

**Comment by gogyzzz** [comment]
@kooBH 일단은 문제점을 기록해두고 내일부터는 예정된 부분을 진행하도록 합시다

**Comment by kooBH** [comment]
해결 : 임시변수 다 추가, 잘못된 수식 수정

**Comment by kooBH** [comment]
```
ffe@FRIST-FROM-ENTRANCE:~/git/OpenBLAS$ sudo make PREFIX=/usr/ install
make -j 8 -f Makefile.install install
make[1]: Entering directory '/home/ffe/git/OpenBLAS'
Generating openblas_config.h in /usr//include
Generating f77blas.h in /usr//include
Generating cblas.h in /usr//include


Copying LAPACKE header files to /usr//include
Copying the static library to /usr//lib



Copying the shared library to /usr//lib
Generating openblas.pc in /usr//lib/pkgconfig
Generating OpenBLASConfig.cmake in /usr//lib/cmake/openblas
Generating OpenBLASConfigVersion.cmake in /usr//lib/cmake/openblas
Install OK!

```

OpenBLAS에는 LAPACKE 포함..
```bash
sudo apt-get install libopenblas-base
```
로 받은 .so 로는 심볼에러가 나고    
위처럼 make로 하면 잘 작동한다
