### ISSUE TITLE
함수이름

### ISSUE THREAD

**Issue by Kandelion** [gogyzzz/iip_sph_pp#96]
new_dim : DIM 을 쓰는가? 쓸건가? 
mem_submat -> mpsubmat?
\ # mp를 그대로 붙이는지 mp_를 붙이는지
mem_MAT     -> mpalloc_mat (memory pool : mp, openmp : mp ??)
 \# 메모리풀과 openmp 둘다 동일한 접두어 사용중

**Comment by gogyzzz** [comment]
@Kandelion 
- openmp의 접두어는 omp로 해주시기 바랍니다.

- mpsubmat으로 해주세요

**Comment by kooBH** [comment]
Done
